
// This file defines types for Firebase Firestore document structures.
// It was previously src/types/supabase.ts

import type { Timestamp } from 'firebase/firestore';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Define interfaces for your Firestore document structures

export interface DecisionDoc {
  id?: string; // Firestore document ID (usually auto-generated by addDoc)
  created_at: Timestamp; 
  name: string;
  email: string;
  decision_type: string;
  comments: string | null;
}

export interface LeadMagnetSignupDoc {
  id?: string;
  created_at: Timestamp;
  email: string;
}

export interface VisitRequestDoc {
  id?: string;
  created_at: Timestamp;
  name: string;
  email: string;
  message: string | null;
}

export interface ExitIntentOfferDoc {
  id?: string;
  created_at: Timestamp;
  email: string; // Can be 'anonymous_prayer_request'
}

export interface WeeklyUpdateSignupDoc {
  id?: string;
  created_at: Timestamp;
  email: string;
  source?: string; 
}

export interface EventDoc { 
  id?: string;
  created_at: Timestamp;
  title: string;
  description: string | null;
  details: string | null; 
  image_src: string | null;
  image_alt: string | null;
  ai_hint: string | null;
  button_text: string | null;
  button_link: string | null;
  event_date: Timestamp; 
  start_time?: string;
  end_time?: string;
}

export interface FinancialPartnerSignupDoc {
  id?: string;
  created_at: Timestamp;
  first_name: string;
  last_name: string;
  email: string;
  phone_number: string | null;
  country: string | null;
}

export interface PrayerPartnerSignupDoc {
  id?: string;
  created_at: Timestamp;
  first_name: string;
  last_name: string;
  email: string;
  committed_to_pray: boolean | null;
}

export interface VolunteerPartnerSignupDoc {
  id?: string;
  created_at: Timestamp;
  first_name: string;
  last_name: string;
  email: string;
  interests_skills: string | null;
}

export interface UserCourseProgressDoc {
  id?: string; 
  created_at: Timestamp;
  user_id: string; // Firebase Auth user.uid
  course_id: string; 
  completed_lessons: number[]; 
  last_accessed: Timestamp;
  progress_percentage: number;
}

export interface FirestoreDocTypes {
  decisions: DecisionDoc;
  lead_magnet_signups: LeadMagnetSignupDoc;
  visit_requests: VisitRequestDoc;
  exit_intent_offers: ExitIntentOfferDoc;
  weekly_updates_signups: WeeklyUpdateSignupDoc;
  financial_partner_signups: FinancialPartnerSignupDoc;
  prayer_partner_signups: PrayerPartnerSignupDoc;
  volunteer_partner_signups: VolunteerPartnerSignupDoc;
  user_course_progress: UserCourseProgressDoc;
}
